# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Point
version:      0.14
version_from: lib/GPS/Point.pm
installdirs:  site
requires:
    Scalar::Util:                  1.02
    strict:                        0
    Test::More:                    0.44
    Test::Number::Delta:           0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
